spring:
  config:
    activate:
      on-profile: prod
  kafka:
    producer:
      bootstrap-servers: host.docker.internal:19092
    consumer:
      bootstrap-servers: host.docker.internal:19092
      group-id: common-listener-id
    bootstrap-servers: host.docker.internal:19092
  data:
    mongodb:
      username: menofsillim
      password: sillim123!
      authentication-database: kafka
      host: host.docker.internal
      database: kafka
      port: 27017
  exposedPort: 30010

