server:
  port: 20010

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger error 해결, 버전 문제
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: common-listener-id