spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: common-listener-id
    bootstrap-servers: localhost:19092
  data:
    mongodb:
      username: menofsillim
      password: sillim123!
      authentication-database: kafka
      host: localhost
      database: kafka
      port: 27017

